server:
  port: 8088
  servlet:
    context-path: /SteamCatAuthority
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: authorityservice
  messages:
    basename: i18n/errormessage
    encoding: utf-8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://81.70.31.60:3306/zhengqimao?useUnicode=true&character_set_server=utf8mb4&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: zhengqimao
    password: s5FYhbJdy6EhzEbA
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      connection-timeout: 30000
      maximum-pool-size: 20
      max-lifetime: 1800000
      minimum-idle: 5
  redis:
    database: 1
    host: 81.70.31.60
    password: rcRSPFcfPZcmXWXi
    port: 6388
    timeout: 3000
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-active: 2000
        max-wait: 1000
  jmx:
    enabled: false

mybatis:
  mapper-locations: classpath:mappers/*.xml

#eureka:
#  instance:
#    # 注册服务使用ip
#    prefer-ip-address: true
#  ###客户端调用地址
#  client:
#    serviceUrl:
#      defaultZone: http://steamcat:Steamcat123@localhost:8100/eureka

steamCatAuthority:
  signKey: steamCat20200808

auth:
  clientId: SteamCat
  clientSecret: se%Smov*da56g48
  domain: 81.70.31.60
  loginUrl: http://127.0.0.1:8080/SteamCatAuthority/oauth/token